### ISSUE TITLE
Register Alias List

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#100]

**Comment by davschneller** [comment]
Hi, a short review only (I don't have much time at the moment):

I like it. All pretty well-commented and so on. Here are still two minor suggestions, no need to implement them:
- The documentation for silent confuses me a bit. Couldn't it reference that changes to the register will not cause a notification?
- Of course, if anyone needs it, there might also be the possibility of a variadic template implementation of the createRegister with aliases method, if this is every needed except for sparing two curly brackets when writing tests for this...

But other than that: keep up the good work and until next time!

**Comment by janschopohl** [comment]
The tests run and I see no issues with this. :+1:
