### ISSUE TITLE
Alphabetic Iterator for Units

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#111]
Add an iterator in a unit, iterating over all RegisterInformations in alphabetical order (will be used by gui)

**Comment by k-lukas** [comment]
Im not very happy, that the `SortedResult` uses pointers. The other possibility would be, to use `std::reference_wrapper`, then you could iterate over the sorted result like this:
`for(RegisterInformation& info : result) { ... }` and no explicit pointer de-referencing would be needed.
But i think there is no "right" way to do it, so you can decide whether to change it or not.

The rest looks good, but again, a little thing about the tests: Rename `UnitInformationTestFixture` to `UnitInformationTest`
