### ISSUE TITLE
Const Memory Area

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#115]

**Comment by janschopohl** [comment]
- Rename the noProtection parameter to something like ignoreProtection [here](https://github.com/TUM-LRR/era-gp-sim/blob/92555a22fc64470ccdc85b3d43d9a8a0e81e5b60/include/core/memory.hpp#L122)
- Why do you initialize [this here](https://github.com/TUM-LRR/era-gp-sim/blob/92555a22fc64470ccdc85b3d43d9a8a0e81e5b60/include/core/memory.hpp#L225)?
- Please make the format of the documentation of private members consistent with everything else and put it in the line above the member
- the loops in the `isProtected` `makeProtected` and `makeUnprotected` seem quite inefficient. Consider using a map with the first address as key and then use `lower_bound` and the value to check if the requested address is within the protected area. Remember that isProtected is called on most calls to `Memory::put`
- Consider renaming `makeUnprotected` to `removeProtection` and the current `removeProtection` to `removeAllProtection`

**Comment by davschneller** [comment]
Got nothing more to add other than the things Jan told you. (the suggested map is probably the method which is the easiest integrated and should give a certain performance boost... Though shouldn't it also work if we got this set here? I mean, we got a pair in it which has its absolute order relation defined, and it's sorted, so it might also work here... Or did I not look at something? Of course, if we say: we always got ultra low memory, we might even clone it, use a bit field for protection, but this leads to bad performance when filling or deleting a section... Oh, of course, what you also might do and might also offer the best performance (and it's complicated), you might even implement a segment tree which might fit here... (though this is absolutely not necessary, if we do not use it that much and with that many regions) But ok, let's not go too complicated, how much is the protection feature actually used?) Apart from them, I like it.

**Comment by janschopohl** [comment]
- what about [this](https://github.com/TUM-LRR/era-gp-sim/blob/3c7e0089c8340532769ff63452de84f4d8baa27f/source/core/memory.cpp#L274) comment? I think you can remove it.
- I think `isProtected` is not perfect because of the linear lookup time, but I guess it is ok for now, as there will probably only be one protected area.
- Why are there no tests for this? (I don't see any)

**Comment by janschopohl** [comment]
Thank you for adding the tests!
You can remove [this](https://github.com/TUM-LRR/era-gp-sim/commit/0aaf224ffe8088e4cf73441dae7c47c0ec88c629#diff-b012a5be3222f19f5e0fdc92fd90d1fdR274), otherwise fine!
