### ISSUE TITLE
32 bit immediates are accepted

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#117]

**Comment by davschneller** [comment]
Yes, that's what it currently does. It accepts 32-bit immediates (why 32? Well, that was a rather sponaneous decision when coding I think #89)  no matter how long the actual immediates are at max. (or did you mean something totally different?)

I do not know if this is remarked when validating, but the parser does nothing in-before to prevent it. This has some specific reason: we do have barely any information about the operands nor the instruction (except the meta information), so it would require to provide some more information about them to us. It would be great if there is another way to resolve this, at least in my opinion.

**Comment by janschopohl** [comment]
ok, it should probably be checked when validating the instruction? Apparently it is not checked at the moment.

**Comment by davschneller** [comment]
What have we planned to do about this issue now? There are now some solutions we could consider:

* Just trim the immediates to the required length after computing them, not bothering what is lying in the upper bits. (I think the trimming should always happen, is it possible in the architecture?).
* Give up the arithmetic compiling.
* Introduce types (probably like `signed` and `unsigned`) to the expression compiler which would be doable (it's templated), but required some time. And conversion would be a problem.
* Just do all the calculations in the required size.

These are probably the things I can remember right now. My favorite for now would be just to trim them. Problem: it might cause barely noticeable behavior.
In the architecture, if I remember correctly, they did check if the last bit in the trimmed immediate equals all the rest of the input memory value. Would it maybe help to rather it the last bit that has been trimmed? This would allow both hexadecimal and decimal input. Only problem would be, that also inputs like `2048` for a 12-Bit immediate would be accepted. But in my opinion, this is not really a misbehavior. Or what to you all others think about that? **EDIT**: Ok, we've discussed that, we do not distinguish between `-1` and `0xffffffff` this way, so this is no alternative.
Why not do all calculations in the required size then?

**Comment by davschneller** [comment]
We think it should work now (at least the error does seem to appear for `0xffffffff` on `hotfix/parser-refactor`). The thing that `0xfff` is not accepted was seen as expected behavior (as we have a signed number).

**Comment by davschneller** [comment]
(i.e. this issue will be closed for now)
