### ISSUE TITLE
Implement redirect pseudo instructions

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#126]
These pseudo instructions will be implemented by a wrapper that redirects/reorders/replaces operands to a underlying existing instruction.
nop, mv, not, neg, negw, sext.w, seqz, snez, sltz, sgtz, beqz, bnez, blez, bgez, bltz, bgtz, j, jr

**Comment by k-lukas** [comment]
Replaced by #136
