### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#14]

**Comment by kreudom** [comment]
Hi, the qml file looks fine to me, I only noticed some typos in the comments in lines 21, 35 and 43. But apart from that I have no issues with it.

**Comment by FelixOpolka** [comment]
Hello,

looks good to me. Just a few points I think might be worth mentioning:
- The ToolButtons for Dec, Hex, Bin etc. contain some duplicate code. It might be worth creating a (inline) component for tool buttons.
- Two versions of QtQuick.Controls are included, I think only one is necessary.
- The width of the ToolButtons for Dec, Hex, Bin etc. is currently adjusted by inserting whitespaces. A better way to accomplish this might be to tweak the label-property and/or background-property of the corresponding ButtonStyle.

**Comment by riedersa** [comment]
Thanks for reviews.
I included the suggested changes except the inline Component. In my opinion it is very difficult to implement the Buttons as such a Component. Then it is very hard, to change the styles of the other buttons. But you are right, it is possible to use if for the text. I also did this.
