### ISSUE TITLE
Parse string arguments

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#140]

**Comment by davschneller** [comment]
Just a little patch for the RISC-V argument parsing. Haven't tested it live yet, and it is difficult to test, I think.

**Comment by kreudom** [comment]
Hi, looks good. Can be merged imo.

**Comment by davschneller** [comment]
(Together in #140, #139 and #148 also in `hotfix/small-parser-fixes`, if somebody else wants to review, if not, I will merge it soon)
