### ISSUE TITLE
Fix jump to labels

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#150]
Branch: [feature/jump-to-label-fix](https://github.com/TUM-LRR/era-gp-sim/tree/feature/jump-to-label-fix)

**Comment by kreudom** [comment]
Hi, thanks for this!

I looked through it and everything looks good. Couldn't really test it, but I don't see any obvious mistakes.

**Comment by ProfPille** [comment]
The code looks just fine :D Keep up the great work
