### ISSUE TITLE
Fix for crashes with directives

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#162]

**Comment by davschneller** [comment]
Hi,
looks good, I like the changes. Some fixes have already been implemented in the branch `hotfix/small-parser-fixes` (originally two commits pushed on `gui-explosive-picnic`, but not on master yet), mind if I merge it in this one?

**Comment by davschneller** [comment]
Now integrated into `hotfix/small-parser-fixes` together with some other small changes.
