### ISSUE TITLE
fix memory bug

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#167]
introduce tryGet, tryPut and trySet to fix crashes in the serialization and deserialization
(and also prepare memory to be used by the pixel display)
[https://github.com/TUM-LRR/era-gp-sim/tree/hotfix/memory](https://github.com/TUM-LRR/era-gp-sim/tree/hotfix/memory)

**Comment by ErikP0** [comment]
Review also for #165:
Looks good !
