### ISSUE TITLE
AUIPC is not implemented correctly

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#189]
AUIPC is supposed to add the given immediate to the program counter, which the current implementation does not do

**Comment by ErikP0** [comment]
Quote from RISC-V specification v2.1: "AUIPC forms a 32-bit offset from the 20-bit U-immediate, filling in the lowest 12 bits with zeros, adds this offset to the pc, then places the **result** in register rd." So auipc can be characterised with `rd = (imm<<12) + pc`. This shows that `pc` itself is **not** changed. ("AUIPC (add upper immediate to pc) is used to build pc-relative addresses", not jumping)
