### ISSUE TITLE
Parse assembler text

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#19]

**Comment by davschneller** [comment]
Looks great! Just one little thing: We have decided to use a prefix `_` instead of a suffix one. (https://github.com/TUM-LRR/era-gp-sim/wiki/Style-Guide) Mind changing that? Apart from that, it's all fine, well-commented, and so on. Of course, it would be nice not to have some big parse method (but rather one built up of many small ones), but I think it is ok here...

**Comment by ErikP0** [comment]
Hi,
everything looks fine. 
An optional thing would be clarify the error message when the line regex does not match. But this would be some effort to check what exactly is invalid (like illegal label definition, missing commas, etc.)
And I have a question: (Where) do you call `AbstractSyntaxTreeNode::validate()`, I didn't find it. In my opinion `syntax-tree-generator.cpp` in line 77 might be a good spot to do so.

**Comment by kreudom** [comment]
Hi,
I changed the code according to your suggestions. Please have another look.

**Comment by kreudom** [comment]
Hmm, the tests seem to fail on travis with gcc. Can't replicate it at home, I'd appreciate it if anyone had suggestions.

**Comment by davschneller** [comment]
The problem with gcc might be fixed (still, I don't know the exact reason), if you changed the line `Architecture testArch("riscv");` to `Architecture testArch = Architecture::Brew(ArchitectureFormula{"riscv", {"rv32i"}});` in syntax-tree-generator-test.cpp Maybe that works... Apart from that, everything now looks fine to me.

**Comment by kreudom** [comment]
Alright, thanks for your help, the tests are passing now.

**Comment by ErikP0** [comment]
I had a look at your changes, they look good
