### ISSUE TITLE
Execution stops after first node

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#210]

**Comment by janschopohl** [comment]
Might not be a bug, as `.section data` and `.section text` was not used in the example program

**Comment by davschneller** [comment]
Shouldn't we at least put in a compile warning? (or even an error)

**Comment by janschopohl** [comment]
@DXIS Yes, I think an error/warning from the parser in this situation would be good. But you should use another issue for that, as this is for line highlighting.
