### ISSUE TITLE
Implement architecture classes

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#24]

**Comment by ErikP0** [comment]
Hi,
I have reviewed your code, I found a major and some minor points to look at.
I would suggest, that you fix architecture-formula.hpp to make it compilable (e.g. use the solution we found together in Slack).
You may rerun your code-formatter on these files, there are just a few lines each strangly formatted, no big deal:
- register-information.hpp
- unit-information.hpp
- container-adapter.hpp
- instructionset.hpp
- utility.hpp
- architecture.cpp

You may as well add a licence header to all source files (we may discuss this in the team if a licence header is mandatory in source files as well).

For the rest, I found nothing to complain about ;)

**Comment by goldsborough** [comment]
Thanks for your points, I'll integrate the changes.
