### ISSUE TITLE
Introduce constant directive

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#51]

**Comment by davschneller** [comment]
Hi,

here's the review: everything's perfect!

Only one little suggestion left: right now, the constant directive works like textual replacement inside an operand, i.e. we could also do like

```
.equ OPENING_BRACKET, )
.equ CLOSING_BRACKET,(
.equ CONSTANT, 1
mov eax, OPENING_BRACKET CONSTANT CLOSING_BRACKET
```

I do not know if we should allow it, but of course trying to parse it in execution phase would maybe prevent that (or maybe throw a warning), maybe using a dummy integer type to prevent overflows. But that's just an idea, it might hinder reusability of the class if we set it fixed to one parser... (I mean, right now, we could use it for any assembly dialect)

Other than that: keep up the good work!

**Comment by kreudom** [comment]
I tried to implement what you suggested, is this what you meant?

**Comment by davschneller** [comment]
Yes, that's great! It's exactly what I meant (even a bit more sophistcated than what I originally thought of as a fix), but it might still need the symbol table symbols to be inserted into the expression.
Of course, one could even check if an arithmetic node is returned. (or allow register nodes)

Oh, there is still one thing I wanted to mention and that is: with arithmetic expressions inside constants, there might be problems, e.g.

```
.equ SUM, 1+2
mov eax, 3*SUM
```

it might evaluate to `5`, b/c the `SUM` constant is inserted without any brackets. Maybe it would be great to put brackets around it (if we want to allow register nodes, then we got to check of course).

**Comment by kreudom** [comment]
Thanks again for your suggestions. I made some adjustments, could you look over it again?

**Comment by davschneller** [comment]
Yes, this is looking good now. (still, now when using `.equ REG, r12` it will fail when inserting it, but will not reject it when executing)

**Comment by ErikP0** [comment]
I have looked over your code, everything looks fine.
