### ISSUE TITLE
Introduce section directive

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#52]

**Comment by davschneller** [comment]
Ok, this was quite trivial, that's why it's been completed so quickly. Just add another thing to the compile state and so on. Might need to be more specific when memory management is available. But maybe this handling can be transferred to the memory reservation directive, so this branch _could_ be done.

No tests for now, as there is almost nothing to test. But if you want some, I can write them.

**Comment by kreudom** [comment]
Hi, everything looks fine to me here.

**Comment by andizimmerer** [comment]
+1 seems alright

**Comment by davschneller** [comment]
Thanks alot! Merged now.
