### ISSUE TITLE
Introduce memory reservation directive

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#53]

**Comment by davschneller** [comment]
I'm gonna move this over here for now. It might still require tests, if not done for all directives at the same time.

Currently it might also be a bit overly-compilcated to preserve the possibility to re-use the class in a future assembler. If you think that this is far too complicated, tell me. I will remove it then immediately.

**Comment by kreudom** [comment]
Looks good to me, tests compile and pass as well. I'll try to merge this into #56 once the other reviewer has given his OK.

**Comment by andizimmerer** [comment]
Everythings looks fine and works. There is nothing to complain about. Good work

**Comment by davschneller** [comment]
Thank you all, it has been merged to #56.
