### ISSUE TITLE
Parse (arbitrary-length) integers

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#54]

**Comment by davschneller** [comment]
Hi again, here's the review:

This looks great so far. Just a few notes:
- Mind consider replacing the `size_t *count` by `size_t &count` and then providing an overloaded method without this parameter? (b/c C++ people seem to like this more)
- There are now exceptions used for catching the errors. Is there any reason to prefer these over a compile error? (other than not having to return something all the time)
- The function seems to do its work properly and it is commented. Here is still another suggestion in case you want to: You may abstract even further (if there will ever be a generic big integer) and separate the prefixes and also the separators etc. But it is not necessary for now, just if you want to make it even more general.

But nevertheless, it looks good. Keep up the good work!

**Comment by kreudom** [comment]
Hi, thanks for your review.

Exceptions are now caught and turned into compile errors.  I also changed the pointers to references where possible.

I like your suggestion of making the parsing function more general, however I won't implement it just now. But I'll come back to it, in case it should be necessary in the future.

**Comment by ErikP0** [comment]
Hi, I have reviewed your code. I did not find any critical issues, the code is commented well, compiles and the tests run.
One really, really minor thing: If called with a start index that is out of range, the parse-code will throw different exceptions and then generate different `CompileError`:
- with `T = int` the template specialization is used and this `std::string{str, start}` throws a `out_of_range`
- with a `T` that is not template specialized your `parseInternal(...)` throws a `invalid_argument`

But like I said, really really minor. I suppose the `IntegerParser` code is not used outside of the parser and the parser can ensure valid start indices, so the user will never be confused by getting different error messages.
So from my point of view, you can merge this feature :)
