### ISSUE TITLE
Parse (arbitrary-length) floats

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#55]

**Comment by davschneller** [comment]
Hi,

to make it short: there's nothing to complain about, perfect! It's commented and formatted, too.

Only a tiny suggestion: just in case, this custom big float comes, we might also need a custom float parser... But as we actually want to near the end of production soon, there might not be time for that so it is merely a suggestion.

Keep up the good work and bye!

**Comment by ErikP0** [comment]
Hi,
this looks good, although I have some suggestions
1. I personally prefer `parseInternal` with no specialization to be implemented and e.g. `assert(false)` or throw an exception indicating that this is not correctly implemented. Not providing an implementation may cause linker errors that are not as clear as a assertion.
2. I'm not sure if our simulator should really use `(-)infinity` string from the STL. I suggest to define our own tokens for that (like `POS_INF`, `NEG_INF`). In theory one could simply replace the tokens with the matching STL counterpart and then parse it. By defining our own tokens, we can somehow control what kind of input the user can give.
3. Every error message provided by a arch validation is enclosed by `QT_TRANSLATE_NOOP("message")` to provide the possibility of translation. In my opinion all parser error messages should be enclosed too. This is not urgent and should not delay this feature. We should discuss this in the next meeting.

**Comment by goldsborough** [comment]
What is the status on this?

**Comment by ErikP0** [comment]
It got two reviews but at that time we chose not to make a floating point risc-v module, so all features that belonged to floating point were dropped.
