### ISSUE TITLE
Parse directives

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#56]

**Comment by davschneller** [comment]
Hi, looking over it I got to say that I like it. The methods are separated and clean (making the review faster to do, sorry for the delay though).

Some minor issues:
- There is a function pointer. Maybe consider replacing it by an `std::function`?
- With the `clone` method I do not feel 100%ly comfortable... (b/c it has to be implemented for every subclass) But I do not see a good way to do it otherwise (except maybe for an external templated method, but ok).
- Might it be possible to even include issue #53, it you like it like it is right now? (it contains something similar to the riscv-directive-factory which can be removed)
- Maybe now issue #79 maybe also pushed to review if it is already included here (and the code of it looks fine as I shortly looked over it at least)
- For the future, we might even add a register alias macro... Just thinking (as the arithmetic constants have brackets around it right now).

Apart from that, I think it is fine (at least I got nothing to complain about), keep up the great work and until next time!

**Comment by davschneller** [comment]
(one thing, which branch will the directive syntax highlighting on? Currently it seems like they are not highlighted, I tried to test it when I temporarily merged this branch locally into the `gui-explosive[...]` one)

**Comment by ErikP0** [comment]
Hi, sorry for the late review:
One little thing: in `riscv-macro-directive-factory.cpp` in line 36, I suggest to replace the expression by `return std::make_unique<T>(params...)`. What you are doing is essentially what `make_unique` does, but it may be more readable to use the `std` template.
As a minor suggestion, I didn't find a test where a macro is not ended with `.endm`. This would not be difficult to test, so I suggest to add it.
Are there tests for the section-directive? If the section directive is easy to test as well, I suggest to perform some testing, if not it would be ok for me to omit those.

EDIT: This review is also for #79

**Comment by kreudom** [comment]
Hi, thanks for your reviews. I tried to implement all your suggestions and fixed some bugs. I'd appreciate it if you could look over it again.

**Comment by ErikP0** [comment]
Looks good :)
