### ISSUE TITLE
Parse C-like strings

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#57]

**Comment by davschneller** [comment]
I'm just gonna put this in review for now to hear your suggestions. Is it OK like that? Would you like that I use more standard library stuff if there is any? Or should I add other methods?

By the way, the build 157 (EDIT: also 158) does not fail b/c of the parsing, it fails b/c of the apparent race in the lock(ed/free) queue. The code-identical 156 build does not fail.

**Comment by kreudom** [comment]
Wow, this is impressive. Looks great to me.

**Comment by davschneller** [comment]
Thanks a lot!
By the way, I have reworked this thing now a little bit (mainly introduced type guards or whatever you call them in C++, so that you cannot put in a string where you want an int), so mind looking over it a bit again? Thanks! I'll also notify the second reviewer so he will look over it and the other patch.

**Comment by davschneller** [comment]
(by the way, string concatenation à la C like `"ab" "c" "defg"` to `"abcdefg"` is not supported, currently)

**Comment by kreudom** [comment]
The changes look good, tests are still all passing. Nothing to complain.

**Comment by andizimmerer** [comment]
There is only one little thing to complain about: include/parser/string-parser.hpp line 86: misleading description of this method
The rest of it looks perfect.

**Comment by davschneller** [comment]
Thank you all for your reviews, it's now merged (and the small comment has been fixed).
