### ISSUE TITLE
Refine CodePosition, LineInterval

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#58]

**Comment by davschneller** [comment]
(this one's been rather a cleanup patch, adds many methods for convenience; should I refactor the rest of the code a bit or is it ok like that and later we implement the stuff?)
Maybe we can merge the three branches together, so it is easier to overview for you reviewers.

**Comment by kreudom** [comment]
Hi, looks fine to me, can be merged in my opinion.

**Comment by andizimmerer** [comment]
I finally found some time reviewing this.
So I noticed some small "issues" (or rather suggestions): code-position.hpp:143 we might check whether this code position is even valid. By now there can be code positions anywhere. I'm not sure if this behaviour is intended but I wanted to mention it. This applies to all four move instructions.
Internal error list: Maybe we should add another parameter, namely startCodePostion and endCodePostion. This adds a lot more flexibility and more accurate information.
+1 for unicorn() :+1: 
In a nutshell: Good work!

**Comment by davschneller** [comment]
Thanks alot for your reviews!

For the code position, I have included an assert when subtracting two code positions and with the moves. As the numbers we use are non-negative, we do not need to check for sums and so. Sadly, for really checking if the code position is inside bounds, it would probably need some info about the text and I do not think that this class is suited for that...

Yes, that's a good idea! We now have a code position interval.

Mind having a look over it once again?

(as a side note: this branch has problems with MSVC (and as one of us would like that), I think I might change them later when the other MSVC branch is on master, maybe as a future work item, as it is not super important; is everyone ok with that?)

**Comment by davschneller** [comment]
(Note: clang-format has not been applied to the latest changes, I will do this as soon as you let it pass)

**Comment by davschneller** [comment]
(another note: the changes have been implemented in the branch of #59)

**Comment by kreudom** [comment]
Still looks good to me, I like the new changes.
