### ISSUE TITLE
Introduce arithmetic parsing

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#59]

**Comment by davschneller** [comment]
Finally, this thing is done... (this branch also contains issue #58)
It also includes a bunch of refactoring and performance improvement when it comes to regexes (mostly setting the optimize flag and making the regexes static const where possible).
(also, there sadly was a small thing about multiple unicorns crashing everything I had fixed for now, please notify me if I have done something wrong... But this also shows that travis builds in release, not in debug mode, but isn't the latter one in this case more suited for CI? Or is really release better and not only for cont. deployment?)
And `expression-compiler.hpp` contains a small explaination why it has these features, `expression-tokenizer.hpp` and `expression-parser.hpp` contain information on how the tokenizing/parsing works respectively.
The multiregex class is a helper whenn there are multiple regexes to be evaluated simultaneously.
Also, there is now a script to change the asserts to the new interface (not for tests so far), called `updateasserts.py` or so.
And for now, it is not connected to the syntax tree generation, we need conversions for that. (and generally, this is maybe something that should be talked: how should we know how big the constants may be at max?)

**Comment by kreudom** [comment]
Implemented some changes here: f730b2c

Looks really good to me now, nothing to complain. Once again very impressive work.
