### ISSUE TITLE
Lock(ed/free) Queue tests fail apparently randomly, do not run on Windows

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#61]
See builds 141, 152 to 155. It happens for both gcc and clang, sometimes only one of them fails, sometimes both. And also the tests that failed seem to vary. Is it possible to fix that? Thank you! (until that, it would be nice to exclude the tests)
Also, the tests do not run on Windows, but as tested it should help to decrease the test size by some factor. I did not want to tamper with your code, but if you want, I could try correct this little problem (but not the one described above with the tests randomly failing on Travis).

**Comment by TobiasHoll** [comment]
Seems to have been a test bug, not anything within the queue. Build 758 passes the tests, but that's obviously not a guarantee. (Hotfix in 504b5c6c6401233903074f8239a395ce09a4dd49)
