### ISSUE TITLE
Implement multiplication/division instructions

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#64]
Add mul(h)  for signed/signed, unsigned/unsigned, signed/unsigned; mulw (only for 64bit).
Add div(u) / rem(u) and div(u)w, rem(u)w

**Comment by ErikP0** [comment]
The 64bit only instructions mulw, div(u)w and rem(u)w will be implemented in a seperate feature.

**Comment by ProfPille** [comment]
Hey, this feature seems to be quite substantial.Let's break it down:

-The documantation could be better formatted, ex:

```
  /**
   * \brief InstructionNodeFactory
   * Creates a Instruction Node Factory for RISC-V architecture
   */
```

```
  /**
   * \brief InstructionNodeFactory Creates a Instruction Node Factory for RISC-V
   *        architecture
   */
```

-the documentation is frequently lacking `\param`

-different documentation styles `/**` and `/*!` are mixedin `instruction-node-factory.hpp`, `integer-instructions.hpp`

-The tests could use some documentation, too

**Comment by k-lukas** [comment]
- I think Peter already mentioned it in Slack: The immediate integer instructions operate on 12 bit immediates, not on 20 bit. Additionally you may change the check for the correct immediate size to the solution i suggested in our meeting, using the conversions. That would remove the problem, that negative immediates fail the tests, as they have bits set in the most significant bits (in their 32 bit representation for example), but would fit into 12 bits theoretically.
- There is some code in the comments in integer-instructions.hpp. You should remove that, if it is no longer needed.
- Please add some more inline documentation to `computeHighOrderBitsOfMultiplication()`
- I think the template parameters could need some better names: Currently, it is `SizeType`, `UnsignedSizeType` and `SignedSizeType`, i would change it to `UnsignedType` and `SignedType` respectively.
- For debug/error messages i would suggest std::cerr, as that stream is not buffered.

Aside from that, the implementation of mul/div looks good, although it is a little mess with the template parameters.

**Comment by goldsborough** [comment]
I've used `UnsignedWord` and `SignedWord`

**Comment by ErikP0** [comment]
Hi,
I have changed the following points in my code:
- I added more comments and fixed the different comment styles where I found them
- The template param names are now `UnsignedWord` and `SignedWord`.
- I removed the code-comments, they were leftovers from a previous attempt that I forgot to delete
- I fixed the 12 bit immediate validation and the tests (I added one extra case for negative immediates) in `temp-arch-dev` and pulled into this feature. Please look at this commit https://github.com/TUM-LRR/era-gp-sim/commit/b0098123e60527236a5a987eda51e0e76ea67cf8 for the implementation.

This feature only focuses on the mul,div,rem instructions - the major part of the test code (especially the stubs/fakes etc) are not part of this feature. I will open an issue for polishing them, though.
Please have another look, if I missed something :)
