### ISSUE TITLE
Implement 64bit only instructions

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#65]
Add addw, sllw, srlw, subw, sraw and respective immediate instructions

**Comment by ErikP0** [comment]
Hi, I have reviewed your code (as Yuri is currently not available).
- As far as I see it, the validation in the `ArchitectureOnlyInstructionNode` should do the same as the validation of `IntegerInstructionNode`. Would it be possible to move one of these implementations into e.g. a seperate (templated) utility function or into `InstructionNode` if thats possible. With this we could reduce the amount of code with the same functionality.
- For the sake of complete tests:
  - Test if `add` is symmetrical (i.e. 4+2 = 2 +4)
  - `TEST(RV64OnlyInstructionsTest, Slr)` should be `TEST(RV64OnlyInstructionsTest, Srl)`, just a typo
  - I suggest to add one more testcase to `srl` to check for sign-extension (e.g.  `(1 << 31) srl 0 == (-1 << 31)`)
- in the test utility function `testRV64OnlyInstructions` I suggest that you check as well that the execution result is indeed a MemoryValue representing the number 0. (Although we did not explicitly define the meaning of `getValue(...)` for a Instruction, I think returning 0 to show that everything succeded is a good habit)
- Another point about the tests: I think there should be more testing for the validation (like immediate boundary tests for the immediate instructions). Have a look at `testIntegerInstructionValidation(...)` and `test12BitImmediateBounds(...)` in <del>`arch-riscv-integer-instructions-tests-cpp`. You may refactor those out into the `dummies.hpp` </del>and then use them for the validation tests.
  EDIT: Did the refactoring for myself, the functions can be found in `arithmetic-test-utils.hpp`, just pull from `temp-arch-dev`

**Comment by riedersa** [comment]
I have reviweded, too.  
Your commentaries are very good and apart from the issues ErikP0 has mentioned, your Code seems to be fine.

**Comment by k-lukas** [comment]
- I totally agree with you, that we should reduce redundancy in our code. But there are some other parts of the code that have to be refactored, so i think we can do this in a seperate feature like `arch-cleanups`
- If i understand the RISCV specification correctly, there is no sign extension at the word shifts. So no need to add some tests there.

I changed the other issues you mentioned. From my view, the feature can be merged.

**Comment by ErikP0** [comment]
- Ok we can do that in a seperate issue
- Well, I really don't know either. I looked at the riscv-tests https://github.com/riscv/riscv-tests/blob/master/isa/rv64ui/slliw.S#L24. In l.24 and l.34 it looks like they expect a sign extended result.  Here is a testcase for srl https://github.com/riscv/riscv-tests/blob/master/isa/rv64ui/srliw.S#L20

The RISCV specification only states "SLLIW, SRLIW, and SRAIW are RV64I-only instructions that are analogously defned but operate on 32-bit values and produce signed 32-bit results.", no word about a 64bit extension.

I think all of our instructions should pass these RISCV-tests.

The rest looks good

**Comment by k-lukas** [comment]
Thanks for the notice. Looking at the official RISC V tests, it seems that they really want arithmetic sign extension even at logical shifting (whut?).
I also changed that, so I think this issues is ready to merge and will be closed.
