### ISSUE TITLE
Implement lockfree task queue

### ISSUE THREAD

**Issue by TobiasHoll** [TUM-LRR/era-gp-sim#7]

**Comment by ProfPille** [comment]
I couldn't find any issues.

**Comment by goldsborough** [comment]
Ok so a small thing is here:

```
using Target = typename std::conditional<std::is_move_assignable<T>::value, T&&, T>::type;
      value = static_cast<Target>(node->value);
```

Wouldn't a plain old `std::move` do exactly what you want? Casting to an rvalue reference would call the move assignment operator if possible, or the copy assignment operator if not (assuming the copy assignment operator declares its argument `const&` and not `&` which is a very reasonable assumption).

I'm more concerned about possible race conditions in `pop`. Specifically here:

```
Node* previous = _head;
      _head = node;
      delete previous;
```

I see two badnesses:
1. Thread A and B both read the same `_head`, then `delete` it twice
2. Thread A reads the `_head`, then assigns it to `node` (`_head->next`), then Thread B reads `previous = _head` as the `_head->next`. Then Thread A deletes `_head` and thread B deletes `_head->next`

This is what you would usually use a lock for of-course. 

Also, any reason why we need our own memory management? I think `std::unique_ptr`s would work quite well and make our resource managment more fun and happy.

**Comment by goldsborough** [comment]
Also, we'll need some tests to merge this :blush:

**Comment by TobiasHoll** [comment]
The `Target` type is wrong, but not for that reason. `std::move` fails if the type cannot be moved. Instead, we need to cast to `const T&`, which `std::move` doesn't do for us.

Also `pop` is not supposed to be thread safe – this is a single-consumer queue, read from by one thread only (see also the comment above `pop`); we don't have the need for a multi-consumer queue in our current project structure.

We use normal pointers because we can't stick a `std::unique_ptr` into an `std::atomic` without losing atomic behavior.
