### ISSUE TITLE
Finish Load Store, LUI and AUPIC

### ISSUE THREAD

**Issue by k-lukas** [TUM-LRR/era-gp-sim#71]

**Comment by ErikP0** [comment]
Hi, I have reviewed your Code and it looks quite solid.
Although I'm not your reviewer, I have a few suggestions:
- I would recommend to rename `SpecialIntegerInstructionNode` to something like `TwoOperandsInstruction(Node)` or `LUIAUIPCValidationNode`. I think the name should roughly describe what functionality this class provides, it is special but there are many "special" instructions in RISCV :)
- You have used `"pc"` as a string literal in your code, I suggest to define it as some kind of `PROGRAM_COUNTER_ID` as constant somewhere in the riscv-code and use that.
- I think there needs to be more testing about the 20bit immediate operand/ in general the validation. You only test if 0 or 1 operand fail and if 2 operands pass, but what about 3 operands, or an immediate operand far greater than 20bit (like `1<<32`) ? Please add more test cases about that as the determination if a value fits into n-bit is a tricky task (see #64)

**Comment by riedersa** [comment]
Hi, i have reviewed too and i have no more notes to ErikP0s review. So seems to be okay

**Comment by k-lukas** [comment]
Regarding the immediates: I changed the check for the immediate size from conversions to checking the bits on the memory value. I strongly suggest, that we transfer those checks into a common file, so every instruction can make use of the check. Then we could test that algorithm separately, and we don't have to rewrite that check for every instructions test file.
But i think that's a topic for another issue (like arch-cleanups).

**Comment by ErikP0** [comment]
I have looked at your changes, from my point of view the feature can be merged.
