### ISSUE TITLE
Implement multiplication/division instructions (word)

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#73]
Implement mulw, div(u)w and rem(u)w

**Comment by ProfPille** [comment]
Okay, let's jump right to the review:
- first of all in `abstract-syntax-tree-node.hpp` l.31 ff. shouldn't be the `std::string& token` `const` and the `MemoryValue value` a `const MemoryValue&`? The `getRegisterValue([...])` itself my be able to be const, too.
- the members of `validation-result.hpp` could be documented
- some of the include guards are `#include ERAGPSIM_..._HPP` and some are `#include ERAGPSIM_..._HPP_`
- There is almost no documentation in `riscv/formats.hpp`
- `riscv/instruction-node.hpp` l.41 may be `getValue(const DummyMemoryAccess& memory_access) const override = 0;`
- this commit still contains an old `include/core/memory-value.hpp` and it seems to think it should replacethe newer one with this
- There is also some Qt related stuff, that might deserve its own commit

**Comment by ErikP0** [comment]
Hi,
thank you for your review, I will look into all of the points you mentioned.
But actually this feature is only about the mulw, and divw / remw instructions which can be found in `include/arch/riscv/mul-div-instructions.hpp`. All the relevant commits are marked with the number of this issue (#73). These are https://github.com/TUM-LRR/era-gp-sim/commit/d2920ae6ea297e86e85e0bf368f7809d503229a1, https://github.com/TUM-LRR/era-gp-sim/commit/66db923a182089959450b639e6a8d1afbd514091, https://github.com/TUM-LRR/era-gp-sim/commit/e7496f1089e51a61923e4ec9086f06d30c1927cd and https://github.com/TUM-LRR/era-gp-sim/commit/cbc236fb06f22bdc2352d28125599e5cb6f8e65f.

The arch-team currently develops on a separate branch using the older version of `MemoryValue` because we need conversions to native types. When conversions are available for the new `MemoryValue`, we'll switch.

**Comment by k-lukas** [comment]
- No no no no no: `set(CMAKE_PREFIX_PATH "~/Qt/5.6/gcc_64/")`. Please use: `-D CMAKE_PREFIX_PATH="~/Qt/5.6/gcc_64/"` when using the cmake executable.
- Sometimes, there are some `iostream` includes, that are marked with "remove this".
- `source/arch/riscv/mul-div-instructions.cpp` and `source/arch/riscv/word-instruction-wrapper.cpp` can be removed

The rest looks good

**Comment by ErikP0** [comment]
Fixed
- Whoopsie, didn't mean to add this one, sorry
- Removed unnecessary includes
- removed empty files
