### ISSUE TITLE
Add information about base extensions

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#76]

**Comment by goldsborough** [comment]
https://github.com/TUM-LRR/era-gp-sim/commit/5433aa788db702683c90528e2809ad4c3a6b50ab

**Comment by ErikP0** [comment]
Hi, I have reviewed the code, it seems to be fine.
Just one little thing that I noticed:
- In `extension-information.cpp` line 226 I would prefer using `return _baseNames.count(extension_name) > 0` over `return _baseNames.count(extension_name);`. I think this expression is more understandable than the implicit bool cast.

I didn't dig deep into the (de)serialization, is the `ExtensionNameCollection` required as well to get (de)serialized or will it be build up the "native"-way (with `merge`) on a deserialization ?

**Comment by goldsborough** [comment]
k
