### ISSUE TITLE
Editor module

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#8]

**Comment by andizimmerer** [comment]
editor-component.cpp:25 - unused import: memory.hpp
editor-component.cpp:98 - may change it to `assert::that(!(this->highlighter));` 
editor-component.cpp:127 - consider using `switch...case` or at least use `else if` for (small) performance increase

**Comment by janschopohl** [comment]
see #103

**Comment by ErikP0** [comment]
Hi, I have reviewd your code. Everything is well documented and it seems to do its job.
One little suggestion: in the `switch case` statement in editor-component:127 you may add a `default case` with a assertion fail for good style.
