### ISSUE TITLE
Improve syntax highlighting interface

### ISSUE THREAD

**Issue by kreudom** [TUM-LRR/era-gp-sim#80]

**Comment by ErikP0** [comment]
Hi, I have reviewed your code.
It looks fine, compiles and tests are good. I like the idea of the `SyntaxInformation` object along with the iterators.
One little thing: I suggest to add a little bit more documentation to `RiscvParser::getSyntaxInformation()` (in the source file). Especially what exactly the regexes do. Example: `"\\b" + instruction.first + "\\b(?!:)"` `//accepts all instruction mnemonics which do not end with a ':'`. Regexes can be a bit hard to read sometimes...

**Comment by kreudom** [comment]
Thanks, I added some descriptions to the regexes. Could you look at it again?

**Comment by davschneller** [comment]
Hi, here's the second review.

All looks commented, the tests pass, so it's great.

About the regexes a few things:
- The immediate regex may need a few more operators (both unary and binary), see the C-like compiler.
- Isn't there the possibility of more labels per line?

But other than that, there's nothing to complain about, keep up the good work!

**Comment by kreudom** [comment]
Thanks for your review.

I added the missing operators. Multiple labels per line won't be supported (as discussed internally).

**Comment by ErikP0** [comment]
For my part (the comments on the regexes) your changes look good.

**Comment by davschneller** [comment]
Yep, the changes also look good to me (though it would be nice to also have `'` for string literals escaped, and maybe also `"` for the reservation directives, if needed; in my opinion you do not need to ask me if you can merge the branch any more if you change this)
