### ISSUE TITLE
Make Registers findable

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#82]

**Comment by goldsborough** [comment]
- [constituent information](https://github.com/TUM-LRR/era-gp-sim/commit/92501709ae217f15007bb2450f15112daf2c18ac)
- [integration into the ISA files](https://github.com/TUM-LRR/era-gp-sim/commit/3c9f973b29cadc7c6cfb710002b942f18e9b73aa)
- [register access from units](https://github.com/TUM-LRR/era-gp-sim/commit/26f699357d2856fd0cf39b6ec235a57b2b12a2c6)
- [tests](https://github.com/TUM-LRR/era-gp-sim/commit/b2eb5ee6248d7904939a70e0684db302bf2b02b6)

**Comment by ErikP0** [comment]
I have reviewed your code, lets begin:
- It is (at least for me) not completely clear what a `enclosingIndex` exactly is. I suppose that it is the start index of the constituent register and that its registerlength can be found in the register with id `_id` ? Please also make sure to define how your indexing works (Little/Big Endian). We had these kind of indexing problems with MemoryValue, so lets not repeat that.
- Do you check/assert (e.g. when adding the `ConstituentInformation` to a `RegisterInformation`) if the constituent register has a valid index within its parent register. Invalid indices would be `index < 0` or `constituentReg.length + index > parentReg.length` ? If not please add this as it makes definition errors in the ISA more likely to be found.
- It seems like that `addConstituent(ConstituentInformation&)` performs the same validation as its template version `addConstituents(Range&)` inside the lambda. You may define a `canBeAdded(Constituent)` member function for this functionality.
- One more minor thing, you could simplify the expression at `ConstituentInformation::operator==(...)` to a single boolean expression

Apart from those points, your feature is good to go!

**Comment by janschopohl** [comment]
I have reviewed the code instead of @TobiasHoll, because he is on vacation.
The tests run fine.
You might want to add an assertion [here](https://github.com/TUM-LRR/era-gp-sim/commit/26f699357d2856fd0cf39b6ec235a57b2b12a2c6#diff-9248ac08ecda25cbd17a827b5992b4e5R128) to check if the searched register exists.

The code is great, thank you for implementing it so fast! :+1:

**Comment by goldsborough** [comment]
- Yes, the `enclosingIndex` is the start index of the constituent within its enclosing register. Actually, I will rename it to `enclosingOffset` to make the **start** bit clearer. Thanks.
- Good catch for the endianness. I think we can keep the bit numbering agnostic to the endianness and stick to [LSB 0](https://en.wikipedia.org/wiki/Bit_numbering) numbering, i.e. bit 0 is always the right-most bit. This definitely makes sense for big endian architectures, but seems to also be the norm for little endian architectures, since "bit 0" also means the right-most bit in x86 (e.g. bit 0 in EAX), even though memory would be stored in little-endian format in that register (i.e. actually in reverse order to how we specify bits when we speak of bits in EAX). So we have two choices here:
  1. Use LSB 0 numbering and have a nice life.
  2. Add the bit numbering (note that this is not an issue with endianness but bit numbering) to the architecture definition.
     Note for this, however, that I think this is more an implementation detail. Even if we were to simulate a MSB 0 architecture, we can nevertheless internally refer to the right most as "bit 0" and specify registers like that in the specification, since this would not be visible to the end user.
     Happy to hear thoughts on this.
- Registers do not have access to their constituent or enclosing registers. These constituent information objects are simply "pointers" so that the core can know how to connect registers together. As such, I can't check if the `enclosing index + length` is still valid. I can check it without the length though.
- Will refactor.
- Thanks, I'll add the existence check.

I will fix what you mentioned and close this issue, since the addition of bit numbering (if you think it makes sense) would be a new feature anyway. Loving the speed (two days for a feature), very nice.
