### ISSUE TITLE
Add signed number representation to architecture

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#84]

**Comment by goldsborough** [comment]
only commit: https://github.com/TUM-LRR/era-gp-sim/commit/32b44de4446c1ff6601a7a43ad2ed2b4efab08d7

**Comment by ErikP0** [comment]
Looks good. I don't know the latest progress of the conversions. If they also define their own SignedRepresentation enums, I think it would be clever to have only one enum for this. So either `ArchitectureProperties::SignedRepresentation` or `ConversionsSignedRepresentation` to prevent the need of converting one enum into the other.

**Comment by goldsborough** [comment]
Hi, thanks. Yes core does know about the discrepancy between those two. We agreed to use the ones from Architecture in our last Hangout on Monday.
