### ISSUE TITLE
Does not compile on MSVC

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#86]

**Comment by davschneller** [comment]
Hi,

a small review for this:
- For the register stuff, the review is in the other issue
- As far as you told me, the tests still fail b/c of the parser part, I might fix that soon (I had no time so far), but I need a bit of time for it.
- Then there is the custom optional. I guess it should be enough for our project though I am not really happy with it, sorry... For example, this class does not work, if `T` has no constructor that takes no arguments, it will simply not compile in this case. (here, a implementation how some people think optional should be: https://github.com/akrzemi1/Optional but it is hard to implement right I guess; so the only way to do this properly would be to include the header file into our external dependencies)

Still, as MSVC is not our primary goal, I hope this implementation will do for now. (also, I do not think it is worth a debate which might be the best replacement when it is then included in the next MSVC version) Also again, probably minGW-w64 or so on Windows would be something to prefer in my opinion, but ok, I have mentioned this enough already internally. So, in my opinion, it may pass (even without the mentioned optional thingy, though that might be nicer if it is allowed).

**Comment by davschneller** [comment]
Still, when I try using this, it keeps giving me errors that /Werror does not exist and that /O2 and another option conflict with each other. Also, the `21st century anyone?` appears for me when I try to use it. When everything mentioned is resolved, strange linker errors appear. I use MSVC 14/2015. Any clue why this happens to me?

**Comment by janschopohl** [comment]
@DXIS The `21st century anyone?` is a cmake error, it only happened to me in QtCreator.

**Comment by janschopohl** [comment]
The optional is not perfect, but I guess it is ok as a short term fix (and because msvc is not our priority right now). We could discuss a third-party solution or something else.
Otherwise I don't see any issues with this branch.

**Comment by goldsborough** [comment]
That beautiful message is thrown when your compiler does not support `--std=c++14`. Please check that it does. Older compilers may only support `--std=c++1y`, which was the unofficial name before the release of C++14. You could `or` the condition, but your compiler should probably support C++14
