### ISSUE TITLE
Architecture Cleanups

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#90]

**Comment by ErikP0** [comment]
Hi, I have reviewed your code. All in all, it looks pretty solid, I like the idea with the `_compute` lambdas as they provide both easy implementation for using native operators and for more difficult implementation that need more expressions.
- To let this branch to compile, I removed the comments before lines 29, 30 in `source/arch/common/CMakeLists.txt`. This should fix the `QtCore/qtglobal.h not found` error.
- My gcc didn't like your `super::_getLower5Bits(...)` in `integer-instructions.hpp` lines 138 & 158. Using `this->_getLower5Bits(...)` and making `_getLower5Bits` `public` seems to do the trick.
- I suggest that you rename `AbstractIntegerInstructionNode::_child(...)` to something like `::getChildValue(...)` as the `getValue()` of a child is returned - not the child itself
- `AbstractIntegerInstructionNode::validateNumberOfChildren` could be renamed to `...NumberOfOperands`
- It seems that the refactoring lost some documentation why `srl` and `sra` were implemented the way they are. I think it is important to document why only unsigned SizeTypes are allowed in `srl` (signed right shift is implementation/compiler specific) and why we implemented `sra` by hand (c++ standard does not define a arithemtic shift operator). Have a look at the "old" documentation.
- `riscv::InstructionFactory::createInstructionNode(...)` doesn't seem to have the same functionality before the refactoring: The old version returned a `nullptr` when a instruction mnemonic was invalid and it transformed the mnemonic first into lowercase before looking for a mapping (and therefore allowing `ADD` to create the matching node). As a refactoring should not change (public visible) behaviour (in this case the parser relies on the nullptr), this should be adapted as well.
- `AbstractIntegerInstructionNode::validateImmediateSize(...)` take a look at #66, especially my mention about `Utility::occupiesMoreBitsThan(...)`. This size test might not work for all values.

**Comment by goldsborough** [comment]
(let's try to use ordered lists for reviews, makes it easier to respond)
1. Great thanks!
2. Thanks yes that is a gcc issue all the time. I will move it into `Utility`, then we also don't need to make it public.
3. Thanks, love to hear about how to make things more expressive.
4. I added the old documentation and a `static_assert` for `SizeType` to be unsigned :blush:.
5. I'm not actually sure that's a good idea to rely on `nullptr`s being returned -- seems like a dirty ("passive") way to check for invalid instruction names. @DXIS couldn't you maybe check in the instruction set or some internal map first, before trying to instantiate the node?
6. Yes I'll respond to that there.

See:
https://github.com/TUM-LRR/era-gp-sim/commit/bd8ee10d3f0bac7efa279694cf09969ad79969f3
https://github.com/TUM-LRR/era-gp-sim/commit/a056a70e71e747efa2140faebace3b31c72b5d02
https://github.com/TUM-LRR/era-gp-sim/commit/b6b266258f1884639e328a74babde7cd8d2a8df9
