### ISSUE TITLE
Arguments for ValidationResult

### ISSUE THREAD

**Issue by k-lukas** [TUM-LRR/era-gp-sim#92]

**Comment by riedersa** [comment]
I have reviewed the commit and can not see any problems. So I think, it is fine.

**Comment by davschneller** [comment]
(also for #93) Yes, this seems to look like a pretty solid implementation! Just a beautification thing: as maybe also mentioned yesterday, there _could_ be a method of `fail` which accepts a variadic template...

**Comment by k-lukas** [comment]
Thanks, i find the syntax of variadic templates soooo ugly, so i left it out. But i will have a look on it

**Comment by k-lukas** [comment]
This feature will be merged with #93
