### ISSUE TITLE
Runtime Validation for the AST

### ISSUE THREAD

**Issue by k-lukas** [TUM-LRR/era-gp-sim#93]

**Comment by ErikP0** [comment]
Hi, this one looks good.
I have a suggestion: Don't make `validateRuntime` `virtual` in `AbstractSyntaxTreeNode` and let it return `validate()` by default. The jump-Instructions can then just override `validateRuntime` when needed. This saves us some declarations down the abstraction chain.

**Comment by k-lukas** [comment]
Good idea to have a default implementation, but i think it shouldn't call `validate()` again, as that method should only tests for runtime errors. And it still needs to be `virtual`, in order to be able to override it, right?
